#!/bin/bash

# Requires sudo
if [ "$EUID" -ne 0 ]; then
    echo Error: wallpaper-slider requires root to install
    exit 1
fi

WPS_HOME_DIR="wallpaperslider"
if [ -d /home/$(logname)/$WPS_HOME_DIR ] && [ -f /usr/local/bin/wallpaper-slider ]; then
    echo
    echo wallpaper-slider: Installed with version $(</home/$(logname)/$WPS_HOME_DIR/data/version.txt)
else
    sudo -u $SUDO_USER cp -r $WPS_HOME_DIR /home/$(logname)
    cp wallpaper-slider /usr/local/bin
    chmod +x /usr/local/bin/wallpaper-slider
    chmod +rwx /home/$(logname)/$WPS_HOME_DIR

    echo
    echo Install successful!
    echo Invoke with "'wallpaper-slider'" command...
    echo
fi

echo
echo Setup:
echo
echo "  Set the wallpaper path: 'wallpaper-slider -p'"
echo "  Set the delay interval: 'wallpaper-slider -d'"
echo "  Activate script: 'wallpaper-slider -r'"
echo