#!/bin/bash

USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
# checks if files exist in home dir, if wallpaper-slider file is in usr/loca/bin
if [ -d $USER_HOME/wallpaper-slider-data ] && [ -f /usr/local/bin/wallpaper-slider ] && [ -f /usr/bin/wallpaper_slider.py ]; then
    echo
    echo wallpaper-slider installed with version $(<$USER_HOME/wallpaper-slider-data/data/version.txt)
    echo invoke with "'wallpaper-slider'" command...
    echo
else
    # requires sudo permissions, run 'sudo ./install'
    cp -r wallpaper-slider-data $USER_HOME
    # CAREFUL, NEXT COMMAND BROKE PC
    # chown $(whoami) $USER_HOME/wallpaper-slider-data
    cp wallpaper-slider /usr/local/bin
    chmod +x /usr/local/bin/wallpaper-slider
    chmod +rwx $USER_HOME/wallpaper-slider-data
    cp wallpaper_slider.py /usr/bin

    echo
    echo wallpaper-slider-gnome installed successfully!
    echo invoke with "'wallpaper-slider'" command...
    echo
fi