#!/bin/bash

# script to setup wallpaper-slider, user can enter the path to their wallpaper directory and a delay
function get_path {
    FORMAT=/path/to/your/wallpapers/WALLPAPERS/
    PATH_PATTERN="^/.*$"
    echo Directory must only contain png, jpeg, svg, tiff, and gif files
    echo Enter full path to wallpapers folder: $FORMAT
    read path
    if [[ $path =~ $PATH_PATTERN ]] && [[ -d "$path" ]]; then

        for file in "$path"/*; do
            if ! [ -f "$file" ]; then
                echo detected subdirectory, terminating process...
                return
            fi

            file_type=$(file -b --mime-type "$file")
            
            if [ "$file_type" != "image/jpeg" ] && [ "$file_type" != "image/png" ] && [ "$file_type" != "image/svg" ] && [ "$file_type" != "image/svg+xml" ] && [ "$file_type" != "image/tiff" ] && [ "$file_type" != "image/gif" ]; then
                echo  detected file format other than png / jpeg / svg, terminating process...
                echo
                echo file: $file
                echo file type: $file_type
                return
            fi
        done

        echo Path to wallpapers: $path
        echo $path | cat > $HOME/wallpaperslider/data/path.txt
        return
    else
        echo Invalid directory. Enter in format $FORMAT
        get_path
    fi
}

function enter_delay {
    FORMAT="Format: '5m' (5 minutes) | '8h' (8 hours) | '1d' (1 day)"
    echo "Enter time delay | [$FORMAT]"
    echo "Example: For an interval of 10 minutes enter '10m'."
    read delay

    delay_length=${#delay}

    # checks $delay contains only integers apart from last char
    for ((i = 0; i < delay_length - 1; i++)); do
        char="${delay:i:1}"
        if ! [[ "$char" =~ [0-9] ]]; then
            echo Invalid. $FORMAT
            enter_delay
        fi
    done

    # writes the entered delay into txt file to be used by wallpaper_slider.py
    if [[ "$delay" == *m ]]; then
        echo Wallpaper change delay: ${delay%?} minutes.
        echo $delay | cat > $HOME/wallpaperslider/data/delay.txt
        return
    elif [[ "$delay" == *h ]]; then
        echo Wallpaper change delay: ${delay%?} hours.
        echo $delay | cat > $HOME/wallpaperslider/data/delay.txt
        return
    elif [[ "$delay" == *d ]]; then
        echo Wallpaper change delay: ${delay%?} days.
        echo $delay | cat > $HOME/wallpaperslider/data/delay.txt
        return
    else
        echo Invalid. $FORMAT
    fi
}

function print_information {
    USER_NAME=$(logname)
    script_name="wallpaper-slider.service"
    service_file_home="/home/$USER_NAME/.config/systemd/user/$script_name"
    service_file_sys="/etc/systemd/user/$script_name"
    delay=$(<$HOME/wallpaperslider/data/delay.txt)
    echo Wallpaper folder path:
    echo $(<$HOME/wallpaperslider/data/path.txt)
    echo Wallpaper change delay:

    if [[ $delay == *m ]]; then
        echo ${delay%?} minutes
    elif [[ $delay == *h ]]; then
        echo ${delay%?} hours
    elif [[ $delay == *d ]]; then
        echo ${delay%?} days
    fi
    echo Set to run on startup?
    if [[ -f $service_file_home ]]; then
        echo True
    elif [[ -f $service_file_sys ]]; then
        echo True
    else
        echo False
    fi

    echo
    echo "-------------------------------------------------------------------------------"
    echo
    echo wallpaper_slider version: $(<$HOME/wallpaperslider/data/version.txt)
    echo
    echo "-------------------------------------------------------------------------------"
    echo
}

function help {
    
    echo
    echo "Options:"
    echo
    echo "-p     Enter path to wallpapers directory."
    echo
    echo "-d     Enter time delay between wallpaper changes in Seconds/Minutes/Hours/Days."
    echo
    echo "-r     Set wallpaper-slider to run on startup. If already set to run on startup, running this command again will remove the startup script (Might require SUDO)."
    echo
    echo "-i     Print user's settings and software information."
    echo
    echo "-h     Print this help."
    echo
}

#make python venv
#TODO, change to system level, fedora gnome does not have user level systemd directory
function run {

    USER_NAME=$(logname)

    script_name="wallpaper-slider.service"
    service_file_home="/home/$USER_NAME/.config/systemd/user/$script_name"
    service_file_sys="/etc/systemd/user/$script_name"
    script_path="/home/$USER_NAME/wallpaperslider/.bin/wallpaper_slider.py"

    if [[ -f $service_file_home ]]; then
        echo wallpaper-slider: deactivating run on startup...
        systemctl --user disable $script_name
        systemctl --user daemon-reload
        rm "$service_file_home"
        exit 0

    elif [[ -f $service_file_sys ]]; then
        echo wallpaper-slider: deactivating run on startup...
        systemctl disable $script_name
        systemctl daemon-reload
        sudo rm "$service_file_sys"
        exit 0;
    fi

    echo wallpaper-slider: setting to run on startup...
    
    # if user's os does not have user level systemd support, run at system level
    if ! [[ -d "/home/$USER_NAME/.config/systemd/" ]]; then
        sudo cat <<EOF > $service_file_sys
[Unit]
Description=Run wallpaper-slider Python script at startup
After=network.target

[Service]
ExecStart=/usr/bin/python3 $script_path
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload
        systemctl enable --now "$script_name"
        exit 0
    fi

    # creates systemmd service file
    cat <<EOF > $service_file_home
[Unit]
Description=Run wallpaper-slider Python script at startup
After=network.target

[Service]
ExecStart=/usr/bin/python3 $script_path
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF


    systemctl --user daemon-reload
    systemctl --user enable --now "$script_name"
}

if [[ $# -eq 0 ]]; then
    echo "wallpaper-slider: try -h for help"
    exit 1
fi

while getopts "p d v i r h" option; do
    case $option in
        p)  # user enters absolute path to wallpapers
            get_path
            exit
            ;;
        
        d)  # user enters time delay
            enter_delay
            exit
            ;;
        
        i)  # displays current settings - path, delay
            print_information
            exit
            ;;

        r)  # runs the program and sets it to run on startup
            run
            exit
            ;;


        h) # display help
            help
            exit
            ;;
        
        *) # if unknown, exits
            echo "wallpaper-slider: wrong invocation, try -h for options."
            exit
            ;;
    esac
done